// <auto-generated />
using System;
using DoAnAsp.Areas.Admin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoAnAsp.Migrations
{
    [DbContext(typeof(DPContext))]
    partial class DPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DoAnAsp.Areas.Admin.Models.BinhLuanModel", b =>
                {
                    b.Property<int>("IdBL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Anh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdSP")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Noidung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdBL");

                    b.HasIndex("IdSP");

                    b.ToTable("binhluan");
                });

            modelBuilder.Entity("DoAnAsp.Areas.Admin.Models.ChiTietHoaDonModel", b =>
                {
                    b.Property<int>("IdCTHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IdHD")
                        .HasColumnType("int");

                    b.Property<int>("IdSP")
                        .HasColumnType("int");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.Property<double>("Tongtien")
                        .HasColumnType("float");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.Property<int?>("hoadonIdHD")
                        .HasColumnType("int");

                    b.HasKey("IdCTHD");

                    b.HasIndex("hoadonIdHD");

                    b.ToTable("chitiethoadon");
                });

            modelBuilder.Entity("DoAnAsp.Areas.Admin.Models.HoaDonModel", b =>
                {
                    b.Property<int>("IdHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Diachi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaylapHD")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Thanhtien")
                        .HasColumnType("float");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.Property<int?>("userIdUser")
                        .HasColumnType("int");

                    b.HasKey("IdHD");

                    b.HasIndex("userIdUser");

                    b.ToTable("hoadon");
                });

            modelBuilder.Entity("DoAnAsp.Areas.Admin.Models.LoaiSPModelcs", b =>
                {
                    b.Property<int>("IdLSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("TenLSP")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("IdLSP");

                    b.ToTable("loaisanpham");
                });

            modelBuilder.Entity("DoAnAsp.Areas.Admin.Models.NhaCungCapModel", b =>
                {
                    b.Property<int>("IdNCC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SdtNCC")
                        .HasColumnType("int");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdNCC");

                    b.ToTable("nhacungcap");
                });

            modelBuilder.Entity("DoAnAsp.Areas.Admin.Models.SanPhamModel", b =>
                {
                    b.Property<int>("IdSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Anh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Donvitinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<int>("IdLSP")
                        .HasColumnType("int");

                    b.Property<int>("IdNCC")
                        .HasColumnType("int");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Soluongton")
                        .HasColumnType("int");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.Property<int?>("loaspIdLSP")
                        .HasColumnType("int");

                    b.Property<int?>("nhacungcapIdNCC")
                        .HasColumnType("int");

                    b.HasKey("IdSP");

                    b.HasIndex("loaspIdLSP");

                    b.HasIndex("nhacungcapIdNCC");

                    b.ToTable("sanpham");
                });

            modelBuilder.Entity("DoAnAsp.Areas.Admin.Models.UserModel", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DiachiUser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotenUser")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PasswordUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SdtUser")
                        .HasColumnType("int");

                    b.Property<bool>("TrangthaiUser")
                        .HasColumnType("bit");

                    b.Property<string>("UsernameUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdUser");

                    b.ToTable("user");
                });

            modelBuilder.Entity("DoAnAsp.Areas.Admin.Views.AdminModel", b =>
                {
                    b.Property<int>("IdAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hoten")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Sdt")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdAdmin");

                    b.ToTable("admin");
                });

            modelBuilder.Entity("DoAnAsp.Areas.Admin.Models.BinhLuanModel", b =>
                {
                    b.HasOne("DoAnAsp.Areas.Admin.Models.SanPhamModel", "sanpham")
                        .WithMany("binhluan")
                        .HasForeignKey("IdSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sanpham");
                });

            modelBuilder.Entity("DoAnAsp.Areas.Admin.Models.ChiTietHoaDonModel", b =>
                {
                    b.HasOne("DoAnAsp.Areas.Admin.Models.HoaDonModel", "hoadon")
                        .WithMany("chitiethoadon")
                        .HasForeignKey("hoadonIdHD");

                    b.Navigation("hoadon");
                });

            modelBuilder.Entity("DoAnAsp.Areas.Admin.Models.HoaDonModel", b =>
                {
                    b.HasOne("DoAnAsp.Areas.Admin.Models.UserModel", "user")
                        .WithMany("hoadon")
                        .HasForeignKey("userIdUser");

                    b.Navigation("user");
                });

            modelBuilder.Entity("DoAnAsp.Areas.Admin.Models.SanPhamModel", b =>
                {
                    b.HasOne("DoAnAsp.Areas.Admin.Models.LoaiSPModelcs", "loasp")
                        .WithMany("sanpham")
                        .HasForeignKey("loaspIdLSP");

                    b.HasOne("DoAnAsp.Areas.Admin.Models.NhaCungCapModel", "nhacungcap")
                        .WithMany("sanpham")
                        .HasForeignKey("nhacungcapIdNCC");

                    b.Navigation("loasp");

                    b.Navigation("nhacungcap");
                });

            modelBuilder.Entity("DoAnAsp.Areas.Admin.Models.HoaDonModel", b =>
                {
                    b.Navigation("chitiethoadon");
                });

            modelBuilder.Entity("DoAnAsp.Areas.Admin.Models.LoaiSPModelcs", b =>
                {
                    b.Navigation("sanpham");
                });

            modelBuilder.Entity("DoAnAsp.Areas.Admin.Models.NhaCungCapModel", b =>
                {
                    b.Navigation("sanpham");
                });

            modelBuilder.Entity("DoAnAsp.Areas.Admin.Models.SanPhamModel", b =>
                {
                    b.Navigation("binhluan");
                });

            modelBuilder.Entity("DoAnAsp.Areas.Admin.Models.UserModel", b =>
                {
                    b.Navigation("hoadon");
                });
#pragma warning restore 612, 618
        }
    }
}
